name: 'Merge Pull Request'
description: 'Automatically merges a PR and posts a celebration message'
author: 'Your Organization'

branding:
  icon: 'git-merge'
  color: 'purple'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  pr-author:
    description: 'Pull request author username'
    required: true
  github-token:
    description: 'GitHub token with merge permissions'
    required: true
  merge-method:
    description: 'Merge method (merge, squash, rebase)'
    required: false
    default: 'squash'

outputs:
  merged:
    description: 'Whether the merge was successful (true/false)'
    value: ${{ steps.merge.outputs.merged }}
  merge-sha:
    description: 'SHA of the merge commit'
    value: ${{ steps.merge.outputs.merge-sha }}

runs:
  using: 'composite'
  steps:
    - name: Merge PR and post celebration
      id: merge
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = parseInt('${{ inputs.pr-number }}');
          const prAuthor = '${{ inputs.pr-author }}';
          const mergeMethod = '${{ inputs.merge-method }}';
          
          const celebrationGifs = [
            'https://c.tenor.com/ZCq4SwgCfxAAAAAC/snoopy-peanuts.gif',
            'https://c.tenor.com/Z0ojZS2kpO0AAAAC/milk-and-mocha-happy.gif',
            'https://c.tenor.com/LffD4a8ET9AAAAAC/heart-celebrate.gif',
            'https://c.tenor.com/HJ0iSKwIG28AAAAC/yes-baby.gif',
            'https://c.tenor.com/4blWuIh5MIYAAAAC/baby-yoda.gif',
            'https://c.tenor.com/B_zYdea4l-4AAAAC/yay-minions.gif',
            'https://media1.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif',
            'https://media2.giphy.com/media/IwAZ6dvvvaTtdI8SD5/giphy.gif',
            'https://media0.giphy.com/media/z8gtBVdZVrH20/giphy.gif',
            'https://media2.giphy.com/media/26gN16cJ6gy4LzZSw/giphy.gif',
            'https://media1.giphy.com/media/LZElUsjl1Bu6c/giphy.gif',
            'https://media1.giphy.com/media/gHnwTttExPf4nwOWm7/giphy.gif',
          ];
          
          const getRandomGif = () => celebrationGifs[Math.floor(Math.random() * celebrationGifs.length)];
          
          const getMergeMessage = (username) => {
            const web_url = 'https://firstcontributions.github.io';
            const codeContributionsLink = 'https://github.com/roshanjossey/code-contributions';
            const fb_share_link = 'https://www.facebook.com/sharer/sharer.php?u=https://roshanjossey.github.io/first-contributions&quote=Yay%21%20I%20just%20made%20my%20first%20open%20source%20contribution%20with%20First%20Contributions.%20You%20can%20too,%20by%20following%20a%20simple%20tutorial%20at%20https%3A//goo.gl/66Axwe&hashtag=%23OpenSource';
            const reddit_link = 'https://www.reddit.com/submit?url=https%3A%2F%2Fgithub.com%2Ffirstcontributions%2Ffirst-contributions&title=Learn%20how%20to%20contribute%20to%20open%20source%20projects%20in%205%20minutes';
            const linkedin_share_link = 'https://www.linkedin.com/sharing/share-offsite/?url=https://github.com/firstcontributions/first-contributions';
            const dev_share_link = "https://dev.to/new?prefill=---%0Atitle%3A%20First%20Contributions%3A%20learn%20how%20to%20contribute%20to%20open%20source%20projects%0Apublished%3A%20true%0Atags%3A%20opensource%2C%20beginners%2C%20tutorial%0A---%0A%0AI%20followed%20the%20hands-on%20tutorial%20in%20the%20Readme%20of%20first%20contributions%20and%20made%20my%20first%20pull%20request%20to%20the%20same%20repo.%0A%0A%0A%7B%25%20embed%20https%3A%2F%2Fgithub.com%2Ffirstcontributions%2Ffirst-contributions%20%25%7D";
            const hackernews_share_link = 'https://news.ycombinator.com/submitlink?u=https%3A%2F%2Fgithub.com%2Ffirstcontributions%2Ffirst-contributions&t=Show%20HN%3A%20Hands%20on%20tutorial%20for%20open%20source%20contribution';
            const bluesky_share_link = 'https://bsky.app/intent/compose?text=Yay%21%20I%20just%20made%20my%20first%20open%20source%20contribution%20with%20%40FirstContributions.%20You%20can%20too%20by%20following%20a%20simple%20tutorial%20at%20https%3A%2F%2Fgoo.gl%2F66Axwe%20%23OpenSource%20%23FirstContribution%20%23Coding%20%23DevCommunity%20%23GitHub%20%23LearnToCode';
            
            const repo_logo = "https://avatars0.githubusercontent.com/u/65761570?s=88&u=640f39b808c75c6b86460aa907dd030bcca2f3c7&v=4";
            const fb_logo = "https://edent.github.io/SuperTinyIcons/images/svg/facebook.svg";
            const reddit_logo = "https://edent.github.io/SuperTinyIcons/images/svg/reddit.svg";
            const linkedin_logo = "https://edent.github.io/SuperTinyIcons/images/svg/linkedin.svg";
            const dev_logo = "https://edent.github.io/SuperTinyIcons/images/svg/dev_to.svg";
            const hackernews_logo = "https://edent.github.io/SuperTinyIcons/images/svg/hackernews.svg";
            const bluesky_logo = "https://edent.github.io/SuperTinyIcons/images/svg/bluesky.svg";
            
            const greeting = `Hello @${username}, congratulations! You've successfully submitted a pull request. 🎉`;
            const starRepoMessage = `If you liked the tutorial, please star this repo by clicking the star button on the top right of this page. <img alt="star screenshot" title="star button" src="https://firstcontributions.github.io/assets/star.png">`;
            
            const nextSteps = `# Next steps \n - Continue contributing: If you're looking for projects to contribute to, checkout our [<img src="${repo_logo}" width="22" title="web app" /> webapp](${web_url}). \n - If you want more practice checkout [code contributions](${codeContributionsLink}). \n - Share on social media: You can share this content to help more people.\n   - [<img alt="bluesky" title="bluesky" src="${bluesky_logo}" width="22"> Post on Bluesky](${bluesky_share_link}).\n   - [<img alt="facebook" title="facebook" src="${fb_logo}" width="22"> share](${fb_share_link}).\n   - [ <img alt="reddit" title="reddit" src="${reddit_logo}" width="22"> share](${reddit_link}).\n   - [<img alt="linkedin" title="linkedin" src="${linkedin_logo}" width="22"> post](${linkedin_share_link}).\n   - [<img alt="devio" title="devio" src="${dev_logo}" width="22"> publish](${dev_share_link}).\n   - [<img src="${hackernews_logo}" width="22" title="HackerNews" /> Post on HackerNews](${hackernews_share_link}).`;
            const feedbackMessage = `We'd love to hear your thoughts about this project. Let us know how we can improve by commenting or opening an issue here.`;
            
            const gif = `![celebration gif](${getRandomGif()})`;
            
            return `${greeting}\n\n${starRepoMessage}\n\n${nextSteps}\n\n${feedbackMessage}\n\n${gif}`;
          };
          
          try {
            console.log(`Attempting to merge PR #${prNumber} using ${mergeMethod} method...`);
            
            const response = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: mergeMethod
            });
            
            if (response.status === 200) {
              console.log("✓ PR merged successfully!");
              core.setOutput("merged", "true");
              core.setOutput("merge-sha", response.data.sha);
              
              const message = getMergeMessage(prAuthor);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: message
              });
              
              console.log("✓ Celebration comment posted!");
            } else {
              throw new Error(`Unexpected status code: ${response.status}`);
            }
          } catch (error) {
            console.error("✗ Error merging pull request:", error.message);
            core.setOutput("merged", "false");
            
            let errMsg = "";
            
            if (error.status === 405 && error.response?.data?.message === "Pull Request is not mergeable") {
              errMsg = `Hello @${prAuthor}, thank you for your pull request. We appreciate your contribution to the project. However, before we can merge it, there is a merge conflict with the target branch.  \n\n No worries! You can follow [this guide](https://github.com/firstcontributions/first-contributions/blob/main/docs/additional-material/git_workflow_scenarios/resolving-merge-conflicts.md) on resolving merge conflicts. Once you've fixed the conflicts and pushed your changes, the repository will check the changes you made and proceed with the merge if everything looks good.  \n\n If you have any questions or need further assistance, don't hesitate to reach out. We're here to help!`;
            } else if (error.status === 409) {
              errMsg = "The pull request has conflicts with the target branch. Resolve the conflicts before merging.";
            } else {
              errMsg = "Something went wrong while merging the pull request. Please check the logs for more details.";
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: errMsg
            });
            
            core.setFailed(error.message);
          }