name: 'Merge Pull Request'
description: 'Automatically merges a PR and posts a celebration message'
author: 'Your Organization'

branding:
  icon: 'git-merge'
  color: 'purple'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  pr-author:
    description: 'Pull request author username'
    required: true
  github-token:
    description: 'GitHub token with merge permissions'
    required: true
  merge-method:
    description: 'Merge method (merge, squash, rebase)'
    required: false
    default: 'squash'

outputs:
  merged:
    description: 'Whether the merge was successful (true/false)'
    value: ${{ steps.merge.outputs.merged }}
  merge-sha:
    description: 'SHA of the merge commit'
    value: ${{ steps.merge.outputs.merge-sha }}

runs:
  using: 'composite'
  steps:
    - name: Merge PR and post celebration
      id: merge
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = parseInt('${{ inputs.pr-number }}', 10);
          const prAuthor = '${{ inputs.pr-author }}';
          const mergeMethod = '${{ inputs.merge-method }}';

          // Centralized asset loader
          let celebrationGifs = [];
          let links = {};
          let logos = {};

          try {
            const assets = require('./merge-pr/lib/assets');
            celebrationGifs = assets.loadGifs() || [];
            links = assets.loadLinks() || {};
            logos = assets.loadLogos() || {};
          } catch (e) {
            console.warn('Could not load assets helper, falling back to inline defaults', e?.message || e);
          }

          // destructure commonly used link/logo properties for easier access
          const {
            web_url = 'https://firstcontributions.github.io',
            codeContributionsLink = 'https://github.com/roshanjossey/code-contributions',
            fb_share_link = '',
            reddit_link = '',
            linkedin_share_link = '',
            dev_share_link = '',
            hackernews_share_link = '',
            bluesky_share_link = ''
          } = links;

          const {
            repo_logo = '',
            fb_logo = '',
            reddit_logo = '',
            linkedin_logo = '',
            dev_logo = '',
            hackernews_logo = '',
            bluesky_logo = ''
          } = logos;

          const getRandomGif = () => {
            if (!Array.isArray(celebrationGifs) || celebrationGifs.length === 0) return '';
            return celebrationGifs[Math.floor(Math.random() * celebrationGifs.length)];
          };

          const getMergeMessage = (username) => {

            const greeting = `Hello @${username}, congratulations! You've successfully submitted a pull request. 🎉`;
            const starRepoMessage = `If you liked the tutorial, please star this repo by clicking the star button on the top right of this page. <img alt="star screenshot" title="star button" src="https://firstcontributions.github.io/assets/star.png">`;

            const nextSteps = `# Next steps \n - Continue contributing: If you're looking for projects to contribute to, checkout our [<img src="${repo_logo}" width="22" title="web app" /> webapp](${web_url}). \n - If you want more practice checkout [code contributions](${codeContributionsLink}). \n - Share on social media: You can share this content to help more people.\n   - [<img alt="bluesky" title="bluesky" src="${bluesky_logo}" width="22"> Post on Bluesky](${bluesky_share_link}).\n   - [<img alt="facebook" title="facebook" src="${fb_logo}" width="22"> share](${fb_share_link}).\n   - [ <img alt="reddit" title="reddit" src="${reddit_logo}" width="22"> share](${reddit_link}).\n   - [<img alt="linkedin" title="linkedin" src="${linkedin_logo}" width="22"> post](${linkedin_share_link}).\n   - [<img alt="devio" title="devio" src="${dev_logo}" width="22"> publish](${dev_share_link}).\n   - [<img src="${hackernews_logo}" width="22" title="HackerNews" /> Post on HackerNews](${hackernews_share_link}).`;
            const feedbackMessage = `We'd love to hear your thoughts about this project. Let us know how we can improve by commenting or opening an issue here.`;

            const gifUrl = getRandomGif();
            const gif = gifUrl ? `![celebration gif](${gifUrl})` : '';

            return `${greeting}\n\n${starRepoMessage}\n\n${nextSteps}\n\n${feedbackMessage}\n\n${gif}`;
          };

          try {
            console.log(`Attempting to merge PR #${prNumber} using ${mergeMethod} method...`);

            const response = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: mergeMethod
            });

            if (response.status === 200) {
              console.log("✓ PR merged successfully!");
              core.setOutput("merged", "true");
              core.setOutput("merge-sha", response.data.sha || '');

              const message = getMergeMessage(prAuthor);

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: message
              });

              console.log("✓ Celebration comment posted!");
            } else {
              throw new Error(`Unexpected status code: ${response.status}`);
            }
          } catch (error) {
            console.error("✗ Error merging pull request:", error?.message || error);
            core.setOutput("merged", "false");

            let errMsg = "Something went wrong while merging the pull request. Please check the logs for more details.";

            if (error?.status === 405 && error?.response?.data?.message === "Pull Request is not mergeable") {
              errMsg = `Hello @${prAuthor}, thank you for your pull request. We appreciate your contribution to the project. However, before we can merge it, there is a merge conflict with the target branch.  \n\n No worries! You can follow [this guide](https://github.com/firstcontributions/first-contributions/blob/main/docs/additional-material/git_workflow_scenarios/resolving-merge-conflicts.md) on resolving merge conflicts. Once you've fixed the conflicts and pushed your changes, the repository will check the changes you made and proceed with the merge if everything looks good.  \n\n If you have any questions or need further assistance, don't hesitate to reach out. We're here to help!`;
            } else if (error?.status === 409) {
              errMsg = "The pull request has conflicts with the target branch. Resolve the conflicts before merging.";
            }

            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: errMsg
              });
            } catch (postErr) {
              console.error('Failed to post error comment:', postErr?.message || postErr);
            }

            core.setFailed(error?.message || String(error));
          }