name: 'Comment on Pull Request'
description: 'Posts a comment on PR when auto-merge is not possible'
author: 'Your Organization'

branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  files-changed:
    description: 'Space-separated list of files changed'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
  comment-header:
    description: 'Custom header for the comment'
    required: false
    default: 'Thank you for your pull request. This pull request contains changes in files which requires review.'

outputs:
  comment-id:
    description: 'ID of the created/updated comment'
    value: ${{ steps.comment.outputs.comment-id }}

runs:
  using: 'composite'
  steps:
    - name: Post or update comment
      id: comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = parseInt('${{ inputs.pr-number }}');
          const filesChanged = '${{ inputs.files-changed }}'.trim();
          const commentHeader = '${{ inputs.comment-header }}';
          
          try {
            // Get existing comments
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            // Find bot comment
            const botComment = comments.find(comment => 
              comment.user.login === 'github-actions[bot]'
            );
            
            // Format files list
            const filesList = filesChanged
              .split(' ')
              .filter(f => f)
              .map(file => `- ${file}`)
              .join('\n');
            
            const body = `${commentHeader}\n\nThe following files were changed:\n\n${filesList}`;
            
            let commentId;
            
            if (botComment) {
              // Update existing comment
              const response = await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
              commentId = response.data.id;
              console.log(`✓ Updated existing comment (ID: ${commentId})`);
            } else {
              // Create new comment
              const response = await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
              commentId = response.data.id;
              console.log(`✓ Created new comment (ID: ${commentId})`);
            }
            
            core.setOutput('comment-id', commentId);
          } catch (error) {
            console.error("✗ Error posting comment:", error.message);
            core.setFailed(error.message);
          }